### ISSUE TITLE
Dynamic background

### ISSUE THREAD

**Issue by MCTaylor17** [MCTaylor17/magic-table#7]
Imagine a screen of any shape.   No imagine a square surrounding it.  Both share a common center and the square can freely rotate.  For any rotation angle, the square must completely cover the screen.

```js
const squareLength = Math.sqrt(Math.pow(winHeight) + Math.pow(winWidth));
const offsetTop = (squareLength - winHeight) / 2 * -1;
const offsetLeft = (squareLength - winWidth) / 2 * -1;
```
```css
#square {
  height: var(--squareLength);
  width: var(--squareLength);
  position: fixed;
  top: var(--offsetTop);
  left: var(--offsetLeft);
  transform-origin: center center;
}
```

Now bind rotation to mouse position and background-position to scrollTop.
